language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - android-22
    - build-tools-22.0.1
    - build-tools-21.1.2
    - build-tools-21.1.1
    - build-tools-21.0.2
    - build-tools-21.0.1
    - build-tools-19.1.0
    - build-tools-19.0.3
    - build-tools-19.0.0
    - extra-android-support
    - extra-android-m2repository

  licenses:
    - android-sdk-license-5be876d5
env:
  # TERM=dumb : For Gradle build output
  - TERM=dumb
  
before_install:
 - echo y | android update sdk -u -a -t android-23
 - echo y | android update sdk -u -a -t build-tools-23.0.2
 - chmod +x gradlew
 
script:
  # Build all gradle-based Android projects
  - ./gradlew build
